// // Import Image
import HeaderFavLogoI from "../static/images/fav.png";
import HeaderLogoI from "../static/images/logo.png";
import NotFoundImageI from "../static/images/404.png";
import aboutusillusI from "../static/images/about-us-illus.png";
import aboutusobj1I from "../static/images/about-us-obj-1.png";
import aboutusobj2I from "../static/images/about-us-obj-2.png";
import leftArrowIconI from "../static/images/icon/left-arrow.png";

// Css Images
import blogdetailsbannerbgI from "../static/images/blog-details-banner-bg.png";
import contactbannerbgI from "../static/images/contact-banner-bg.png";
import gamesbannerbgI from "../static/images/games-banner-bg.png";
import indexbannerbgI from "../static/images/index-banner-bg.png";
import lotterybannerbgI from "../static/images/lottery-banner-bg.png";
import promotionsbannerbgI from "../static/images/promotions-banner-bg.png";
import tournamentbannerbgI from "../static/images/tournament-banner-bg.png";
import btnbgI from "../static/images/btn-bg.png";
import counterballI from "../static/images/counter-ball.png";
import counterlightI from "../static/images/counter-light.png";
import dropswinsbgI from "../static/images/drops-wins-bg.png";
import featuresbgI from "../static/images/features-bg.png";


import blogpostimage1I from "../static/images/blog-post-image-1.png";


import errorbgI from "../static/images/error-bg.png";
import favI from "../static/images/fav.png";
import finishedtournamentsbgI from "../static/images/finished-tournaments-bg.png";
import footerbgI from "../static/images/footer-bg.png";
import footerformbgI from "../static/images/footer-form-bg.png";
import gamesbgI from "../static/images/games-bg.png";
import getstartbgI from "../static/images/get-start-bg.png";
import getstartillusI from "../static/images/get-start-illus.png";
import jackpotbgI from "../static/images/jackpot-bg.png";
import jackpoticonI from "../static/images/jackpot-icon.png";
import jackpotimage1I from "../static/images/jackpot-image-1.png";
import jackpotimage2I from "../static/images/jackpot-image-2.png";
import jackpotimage3I from "../static/images/jackpot-image-3.png";
import jackpotimage4I from "../static/images/jackpot-image-4.png";
import jackpotsecbgI from "../static/images/jackpot-sec-bg.png";
import latestbetsbgI from "../static/images/latest-bets-bg.png";
import playerscircleI from "../static/images/players-circle.png";
import playersimg1I from "../static/images/players-img-1.png";
import playersimg2I from "../static/images/players-img-2.png";
import playersimg3I from "../static/images/players-img-3.png";
import populargamebgI from "../static/images/popular-game-bg.png";
import populargameimage1I from "../static/images/popular-game-image-1.png";
import populargameimage2I from "../static/images/popular-game-image-2.png";
import populargameimage3I from "../static/images/popular-game-image-3.png";
import populargameimage4I from "../static/images/popular-game-image-4.png";
import populargameimage5I from "../static/images/popular-game-image-5.png";
import populargameimage6I from "../static/images/popular-game-image-6.png";
import populargameitemI from "../static/images/popular-game-item.png";
import preloaderI from "../static/images/preloader.gif";
import profileimageI from "../static/images/profile-image.png";
import referillusI from "../static/images/refer-illus.png";
import refershapeI from "../static/images/refer-shape.png";
import tournamentheadbgI from "../static/images/tournament-head-bg.png";
import tournamentillusI from "../static/images/tournament-illus.png";
// Icon
import SendIconI from "../static/images/icon/send-icon.png";
import btcicon2I from "../static/images/icon/btc-icon-2.png";
import btcicon3I from "../static/images/icon/btc-icon-3.png";
import checkI from "../static/images/icon/check.png";
import countericon1I from "../static/images/icon/counter-icon-1.png";
import countericon2I from "../static/images/icon/counter-icon-2.png";
import dashI from "../static/images/icon/dash.png";
import downarrowI from "../static/images/icon/down-arrow.png";
import emailiconI from "../static/images/icon/email-icon.png";
import etcI from "../static/images/icon/etc.png";
import facebookI from "../static/images/icon/facebook.png";
import featuresicon1I from "../static/images/icon/features-icon-1.png";
import featuresicon2I from "../static/images/icon/features-icon-2.png";
import featuresicon3I from "../static/images/icon/features-icon-3.png";
import featuresicon4I from "../static/images/icon/features-icon-4.png";
import gamestabicon1I from "../static/images/icon/games-tab-icon-1.png";
import gamestabicon2I from "../static/images/icon/games-tab-icon-2.png";
import gamestabicon3I from "../static/images/icon/games-tab-icon-3.png";
import gamestabicon4I from "../static/images/icon/games-tab-icon-4.png";
import gamestabicon5I from "../static/images/icon/games-tab-icon-5.png";
import gamestabicon6I from "../static/images/icon/games-tab-icon-6.png";
import gamestabicon7I from "../static/images/icon/games-tab-icon-7.png";
import gamestabicon8I from "../static/images/icon/games-tab-icon-8.png";
import howworksarrow1I from "../static/images/icon/how-works-arrow-1.png";
import howworksarrow2I from "../static/images/icon/how-works-arrow-2.png";
import howworksicon1I from "../static/images/icon/how-works-icon-1.png";
import howworksicon2I from "../static/images/icon/how-works-icon-2.png";
import howworksicon3I from "../static/images/icon/how-works-icon-3.png";
import howworksicon4I from "../static/images/icon/how-works-icon-4.png";
import howworksicon5I from "../static/images/icon/how-works-icon-5.png";
import howworksicon6I from "../static/images/icon/how-works-icon-6.png";
import infoicon1I from "../static/images/icon/info-icon-1.png";
import infoicon2I from "../static/images/icon/info-icon-2.png";
import instagramI from "../static/images/icon/instagram.png";
import playiconI from "../static/images/icon/play-icon.png";
import plusiconI from "../static/images/icon/plus-icon.png";
import prizeicon1I from "../static/images/icon/prize-icon-1.png";
import prizeicon2I from "../static/images/icon/prize-icon-2.png";
import prizeicon3I from "../static/images/icon/prize-icon-3.png";
import rightarrowI from "../static/images/icon/right-arrow.png";
import rightarrow2I from "../static/images/icon/right-arrow-2.png";
import searchiconI from "../static/images/icon/search-icon.png";
import searchicon2I from "../static/images/icon/search-icon-2.png";
import securityI from "../static/images/icon/security.png";
import sendiconI from "../static/images/icon/send-icon.png";
import tournamentgamesicon1I from "../static/images/icon/tournament-games-icon-1.png";
import tournamentgamesicon2I from "../static/images/icon/tournament-games-icon-2.png";
import trxI from "../static/images/icon/trx.png";
import twitterI from "../static/images/icon/twitter.png";
import whychooseicon1I from "../static/images/icon/why-choose-icon-1.png";
import whychooseicon2I from "../static/images/icon/why-choose-icon-2.png";
import whychooseicon3I from "../static/images/icon/why-choose-icon-3.png";
import whychooseicon4I from "../static/images/icon/why-choose-icon-4.png";
import whychooseicon5I from "../static/images/icon/why-choose-icon-5.png";
import whychooseicon6I from "../static/images/icon/why-choose-icon-6.png";
import winicon1I from "../static/images/icon/win-icon-1.png";
import winicon2I from "../static/images/icon/win-icon-2.png";
import winicon3I from "../static/images/icon/win-icon-3.png";
import btciconI from "../static/images/icon/btc-icon.png";

// New Added Icon
import fullScreenI from "../static/images/icon/fullscreen.png";
import exitFullscreenI from "../static/images/icon/exit-fullscreen.png";

// // Export Image
export const fullscreen = fullScreenI;
export const exitFullscreen = exitFullscreenI;
export const HeaderFavLogo = HeaderFavLogoI;
export const HeaderLogo = HeaderLogoI;
export const NotFoundImage = NotFoundImageI;
export const aboutusillus = aboutusillusI;
export const aboutusobj1 = aboutusobj1I;
export const aboutusobj2 = aboutusobj2I;
export const blogdetailsbannerbg = blogdetailsbannerbgI;
export const leftArrowIcon = leftArrowIconI;

export const blogpostimage1 = blogpostimage1I;

export const btnbg = btnbgI;
export const contactbannerbg = contactbannerbgI;
export const counterball = counterballI;
export const counterlight = counterlightI;
export const dropswinsbg = dropswinsbgI;
export const errorbg = errorbgI;
export const fav = favI;
export const featuresbg = featuresbgI;
export const finishedtournamentsbg = finishedtournamentsbgI;
export const footerbg = footerbgI;
export const footerformbg = footerformbgI;
export const gamesbannerbg = gamesbannerbgI;
export const gamesbg = gamesbgI;
export const getstartbg = getstartbgI;
export const getstartillus = getstartillusI;
export const indexbannerbg = indexbannerbgI;
export const jackpotbg = jackpotbgI;
export const jackpoticon = jackpoticonI;
export const jackpotimage1 = jackpotimage1I;
export const jackpotimage2 = jackpotimage2I;
export const jackpotimage3 = jackpotimage3I;
export const jackpotimage4 = jackpotimage4I;
export const jackpotsecbg = jackpotsecbgI;
export const latestbetsbg = latestbetsbgI;
export const lotterybannerbg = lotterybannerbgI;
export const playerscircle = playerscircleI;
export const playersimg1 = playersimg1I;
export const playersimg2 = playersimg2I;
export const playersimg3 = playersimg3I;
export const populargamebg = populargamebgI;
export const populargameimage1 = populargameimage1I;
export const populargameimage2 = populargameimage2I;
export const populargameimage3 = populargameimage3I;
export const populargameimage4 = populargameimage4I;
export const populargameimage5 = populargameimage5I;
export const populargameimage6 = populargameimage6I;
export const populargameitem = populargameitemI;
export const preloader = preloaderI;
export const profileimage = profileimageI;
export const promotionsbannerbg = promotionsbannerbgI;
export const referillus = referillusI;
export const refershape = refershapeI;
export const tournamentbannerbg = tournamentbannerbgI;
export const tournamentheadbg = tournamentheadbgI;
export const tournamentillus = tournamentillusI;

// Icon
export const SendIcon = SendIconI;
export const btcicon2 = btcicon2I;
export const btcicon3 = btcicon3I;
export const check = checkI;
export const countericon1 = countericon1I;
export const countericon2 = countericon2I;
export const dash = dashI;
export const downarrow = downarrowI;
export const emailicon = emailiconI;
export const etc = etcI;
export const facebook = facebookI;
export const featuresicon1 = featuresicon1I;
export const featuresicon2 = featuresicon2I;
export const featuresicon3 = featuresicon3I;
export const featuresicon4 = featuresicon4I;
export const gamestabicon1 = gamestabicon1I;
export const gamestabicon2 = gamestabicon2I;
export const gamestabicon3 = gamestabicon3I;
export const gamestabicon4 = gamestabicon4I;
export const gamestabicon5 = gamestabicon5I;
export const gamestabicon6 = gamestabicon6I;
export const gamestabicon7 = gamestabicon7I;
export const gamestabicon8 = gamestabicon8I;
export const howworksarrow1 = howworksarrow1I;
export const howworksarrow2 = howworksarrow2I;
export const howworksicon1 = howworksicon1I;
export const howworksicon2 = howworksicon2I;
export const howworksicon3 = howworksicon3I;
export const howworksicon4 = howworksicon4I;
export const howworksicon5 = howworksicon5I;
export const howworksicon6 = howworksicon6I;
export const infoicon1 = infoicon1I;
export const infoicon2 = infoicon2I;
export const instagram = instagramI;
export const playicon = playiconI;
export const plusicon = plusiconI;
export const prizeicon1 = prizeicon1I;
export const prizeicon2 = prizeicon2I;
export const prizeicon3 = prizeicon3I;
export const rightarrow = rightarrowI;
export const rightarrow2 = rightarrow2I;
export const searchicon = searchiconI;
export const searchicon2 = searchicon2I;
export const security = securityI;
export const sendicon = sendiconI;
export const tournamentgamesicon1 = tournamentgamesicon1I;
export const tournamentgamesicon2 = tournamentgamesicon2I;
export const trx = trxI;
export const twitter = twitterI;
export const whychooseicon1 = whychooseicon1I;
export const whychooseicon2 = whychooseicon2I;
export const whychooseicon3 = whychooseicon3I;
export const whychooseicon4 = whychooseicon4I;
export const whychooseicon5 = whychooseicon5I;
export const whychooseicon6 = whychooseicon6I;
export const winicon1 = winicon1I;
export const winicon2 = winicon2I;
export const winicon3 = winicon3I;
export const btcicon = btciconI;
