// // Import Image
import HeaderFavLogoI from "../static/images/fav.png";
import HeaderLogoI from "../static/images/logo.png";
import NotFoundI from "../static/images/404.png";
import aboutusbannerbgI from "../static/images/about-us-banner-bg.png";
import aboutusillusI from "../static/images/about-us-illus.png";
import aboutusobj1I from "../static/images/about-us-obj-1.png";
import aboutusobj2I from "../static/images/about-us-obj-2.png";
import blogbannerbgI from "../static/images/blog-banner-bg.png";
import blogdetailsbannerbgI from "../static/images/blog-details-banner-bg.png";
import blogpostimage1I from "../static/images/blog-post-image-1.png";
import blogpostimage2I from "../static/images/blog-post-image-2.png";
import blogpostimage3I from "../static/images/blog-post-image-3.png";
import blogpostimage4I from "../static/images/blog-post-image-4.png";
import blogpostimage5I from "../static/images/blog-post-image-5.png";
import blogpostimage6I from "../static/images/blog-post-image-6.png";
import blogpostimage7I from "../static/images/blog-post-image-7.png";
import blogpostimage8I from "../static/images/blog-post-image-8.png";
import blogpostimage9I from "../static/images/blog-post-image-9.png";
import blogpostimage10I from "../static/images/blog-post-image-10.png";
import blogpostimage11I from "../static/images/blog-post-image-11.png";
import blogpostimage12I from "../static/images/blog-post-image-12.png";
import btnbgI from "../static/images/btn-bg.png";
import contactbannerbgI from "../static/images/contact-banner-bg.png";
import counterballI from "../static/images/counter-ball.png";
import counterlightI from "../static/images/counter-light.png";
import dropswinsbgI from "../static/images/drops-wins-bg.png";
import errorbgI from "../static/images/error-bg.png";
import favI from "../static/images/fav.png";
import featuresbgI from "../static/images/features-bg.png";
import finishedtournamentsbgI from "../static/images/finished-tournaments-bg.png";
import finishedtournamentsimg1I from "../static/images/finished-tournaments-img-1.png";
import finishedtournamentsimg2I from "../static/images/finished-tournaments-img-2.png";
import finishedtournamentsimg3I from "../static/images/finished-tournaments-img-3.png";
import finishedtournamentsimg4I from "../static/images/finished-tournaments-img-4.png";
import footerbgI from "../static/images/footer-bg.png";
import footerformbgI from "../static/images/footer-form-bg.png";
import gamesbannerbgI from "../static/images/games-banner-bg.png";
import gamesbgI from "../static/images/games-bg.png";
import gameslogo1I from "../static/images/games-logo-1.png";
import gameslogo2I from "../static/images/games-logo-2.png";
import gameslogo3I from "../static/images/games-logo-3.png";
import gameslogo4I from "../static/images/games-logo-4.png";
import gameslogo5I from "../static/images/games-logo-5.png";
import gameslogo6I from "../static/images/games-logo-6.png";
import gameslogo7I from "../static/images/games-logo-7.png";
import gameslogo8I from "../static/images/games-logo-8.png";
import gameslogo9I from "../static/images/games-logo-9.png";
import gameslogo10I from "../static/images/games-logo-10.png";
import gameslogo11I from "../static/images/games-logo-11.png";
import gameslogo12I from "../static/images/games-logo-12.png";
import gameslogo13I from "../static/images/games-logo-13.png";
import gameslogo14I from "../static/images/games-logo-14.png";
import gameslogo15I from "../static/images/games-logo-15.png";
import gameslogo16I from "../static/images/games-logo-16.png";
import gameslogo17I from "../static/images/games-logo-17.png";
import gameslogo18I from "../static/images/games-logo-18.png";
import getstartbgI from "../static/images/get-start-bg.png";
import getstartillusI from "../static/images/get-start-illus.png";
import indexbannerbgI from "../static/images/index-banner-bg.png";
import jackpotbgI from "../static/images/jackpot-bg.png";
import jackpoticonI from "../static/images/jackpot-icon.png";
import jackpotimage1I from "../static/images/jackpot-image-1.png";
import jackpotimage2I from "../static/images/jackpot-image-2.png";
import jackpotimage3I from "../static/images/jackpot-image-3.png";
import jackpotimage4I from "../static/images/jackpot-image-4.png";
import jackpotsecbgI from "../static/images/jackpot-sec-bg.png";
import latestbetsbgI from "../static/images/latest-bets-bg.png";
import lotterybannerbgI from "../static/images/lottery-banner-bg.png";
import playerscircleI from "../static/images/players-circle.png";
import playersimg1I from "../static/images/players-img-1.png";
import playersimg2I from "../static/images/players-img-2.png";
import playersimg3I from "../static/images/players-img-3.png";
import populargamebgI from "../static/images/popular-game-bg.png";
import populargameimage1I from "../static/images/popular-game-image-1.png";
import populargameimage2I from "../static/images/popular-game-image-2.png";
import populargameimage3I from "../static/images/popular-game-image-3.png";
import populargameimage4I from "../static/images/popular-game-image-4.png";
import populargameimage5I from "../static/images/popular-game-image-5.png";
import populargameimage6I from "../static/images/popular-game-image-6.png";
import populargameitemI from "../static/images/popular-game-item.png";
import preloaderI from "../static/images/preloader.gif";
import profileimageI from "../static/images/profile-image.png";
import promotionsbannerbgI from "../static/images/promotions-banner-bg.png";
import promotionsillus1I from "../static/images/promotions-illus-1.png";
import promotionsillus2I from "../static/images/promotions-illus-2.png";
import promotionsillus3I from "../static/images/promotions-illus-3.png";
import promotionsillus4I from "../static/images/promotions-illus-4.png";
import promotionsillus5I from "../static/images/promotions-illus-5.png";
import promotionsillus6I from "../static/images/promotions-illus-6.png";
import promotionsillus7I from "../static/images/promotions-illus-7.png";
import promotionsillus8I from "../static/images/promotions-illus-8.png";
import promotionsillus9I from "../static/images/promotions-illus-9.png";
import referillusI from "../static/images/refer-illus.png";
import refershapeI from "../static/images/refer-shape.png";
import tableimage1I from "../static/images/table-image-1.png";
import tableimage2I from "../static/images/table-image-2.png";
import tableimage3I from "../static/images/table-image-3.png";
import tableimage4I from "../static/images/table-image-4.png";
import tableimage5I from "../static/images/table-image-5.png";
import tableimage6I from "../static/images/table-image-6.png";
import tableimage7I from "../static/images/table-image-7.png";
import tableimage8I from "../static/images/table-image-8.png";
import tableimage9I from "../static/images/table-image-9.png";
import tableimage10I from "../static/images/table-image-10.png";
import tournamentbannerbgI from "../static/images/tournament-banner-bg.png";
import tournamentheadbgI from "../static/images/tournament-head-bg.png";
import tournamentillusI from "../static/images/tournament-illus.png";
import tournamentimg1I from "../static/images/tournament-img-1.png";
import tournamentimg2I from "../static/images/tournament-img-2.png";
import tournamentimg3I from "../static/images/tournament-img-3.png";
import tournamentimg4I from "../static/images/tournament-img-4.png";
import weeklylotterybgI from "../static/images/weekly-lottery-bg.png";
// Icon
import SendIconI from "../static/images/icon/send-icon.png";
import btcicon2I from "../static/images/icon/btc-icon-2.png";
import btcicon3I from "../static/images/icon/btc-icon-3.png";
import checkI from "../static/images/icon/check.png";
import countericon1I from "../static/images/icon/counter-icon-1.png";
import countericon2I from "../static/images/icon/counter-icon-2.png";
import dashI from "../static/images/icon/dash.png";
import downarrowI from "../static/images/icon/down-arrow.png";
import emailiconI from "../static/images/icon/email-icon.png";
import etcI from "../static/images/icon/etc.png";
import facebookI from "../static/images/icon/facebook.png";
import featuresicon1I from "../static/images/icon/features-icon-1.png";
import featuresicon2I from "../static/images/icon/features-icon-2.png";
import featuresicon3I from "../static/images/icon/features-icon-3.png";
import featuresicon4I from "../static/images/icon/features-icon-4.png";
import gamestabicon1I from "../static/images/icon/games-tab-icon-1.png";
import gamestabicon2I from "../static/images/icon/games-tab-icon-2.png";
import gamestabicon3I from "../static/images/icon/games-tab-icon-3.png";
import gamestabicon4I from "../static/images/icon/games-tab-icon-4.png";
import gamestabicon5I from "../static/images/icon/games-tab-icon-5.png";
import gamestabicon6I from "../static/images/icon/games-tab-icon-6.png";
import gamestabicon7I from "../static/images/icon/games-tab-icon-7.png";
import gamestabicon8I from "../static/images/icon/games-tab-icon-8.png";
import howworksarrow1I from "../static/images/icon/how-works-arrow-1.png";
import howworksarrow2I from "../static/images/icon/how-works-arrow-2.png";
import howworksicon1I from "../static/images/icon/how-works-icon-1.png";
import howworksicon2I from "../static/images/icon/how-works-icon-2.png";
import howworksicon3I from "../static/images/icon/how-works-icon-3.png";
import howworksicon4I from "../static/images/icon/how-works-icon-4.png";
import howworksicon5I from "../static/images/icon/how-works-icon-5.png";
import howworksicon6I from "../static/images/icon/how-works-icon-6.png";
import infoicon1I from "../static/images/icon/info-icon-1.png";
import infoicon2I from "../static/images/icon/info-icon-2.png";
import instagramI from "../static/images/icon/instagram.png";
import playiconI from "../static/images/icon/play-icon.png";
import plusiconI from "../static/images/icon/plus-icon.png";
import prizeicon1I from "../static/images/icon/prize-icon-1.png";
import prizeicon2I from "../static/images/icon/prize-icon-2.png";
import prizeicon3I from "../static/images/icon/prize-icon-3.png";
import rightarrowI from "../static/images/icon/right-arrow.png";
import rightarrow2I from "../static/images/icon/right-arrow-2.png";
import searchiconI from "../static/images/icon/search-icon.png";
import searchicon2I from "../static/images/icon/search-icon-2.png";
import securityI from "../static/images/icon/security.png";
import sendiconI from "../static/images/icon/send-icon.png";
import tournamentgamesicon1I from "../static/images/icon/tournament-games-icon-1.png";
import tournamentgamesicon2I from "../static/images/icon/tournament-games-icon-2.png";
import trxI from "../static/images/icon/trx.png";
import twitterI from "../static/images/icon/twitter.png";
import whychooseicon1I from "../static/images/icon/why-choose-icon-1.png";
import whychooseicon2I from "../static/images/icon/why-choose-icon-2.png";
import whychooseicon3I from "../static/images/icon/why-choose-icon-3.png";
import whychooseicon4I from "../static/images/icon/why-choose-icon-4.png";
import whychooseicon5I from "../static/images/icon/why-choose-icon-5.png";
import whychooseicon6I from "../static/images/icon/why-choose-icon-6.png";
import winicon1I from "../static/images/icon/win-icon-1.png";
import winicon2I from "../static/images/icon/win-icon-2.png";
import winicon3I from "../static/images/icon/win-icon-3.png";
import btciconI from "../static/images/icon/btc-icon.png";

// // Export Image
export const HeaderFavLogo = HeaderFavLogoI;
export const HeaderLogo = HeaderLogoI;
export const NotFound = NotFoundI;
export const aboutusbannerbg = aboutusbannerbgI;
export const aboutusillus = aboutusillusI;
export const aboutusobj1 = aboutusobj1I;
export const aboutusobj2 = aboutusobj2I;
export const blogbannerbg = blogbannerbgI;
export const blogdetailsbannerbg = blogdetailsbannerbgI;
export const blogpostimage1 = blogpostimage1I;
export const blogpostimage2 = blogpostimage2I;
export const blogpostimage3 = blogpostimage3I;
export const blogpostimage4 = blogpostimage4I;
export const blogpostimage5 = blogpostimage5I;
export const blogpostimage6 = blogpostimage6I;
export const blogpostimage7 = blogpostimage7I;
export const blogpostimage8 = blogpostimage8I;
export const blogpostimage9 = blogpostimage9I;
export const blogpostimage10 = blogpostimage10I;
export const blogpostimage11 = blogpostimage11I;
export const blogpostimage12 = blogpostimage12I;
export const btnbg = btnbgI;
export const contactbannerbg = contactbannerbgI;
export const counterball = counterballI;
export const counterlight = counterlightI;
export const dropswinsbg = dropswinsbgI;
export const errorbg = errorbgI;
export const fav = favI;
export const featuresbg = featuresbgI;
export const finishedtournamentsbg = finishedtournamentsbgI;
export const finishedtournamentsimg1 = finishedtournamentsimg1I;
export const finishedtournamentsimg2 = finishedtournamentsimg2I;
export const finishedtournamentsimg3 = finishedtournamentsimg3I;
export const finishedtournamentsimg4 = finishedtournamentsimg4I;
export const footerbg = footerbgI;
export const footerformbg = footerformbgI;
export const gamesbannerbg = gamesbannerbgI;
export const gamesbg = gamesbgI;
export const gameslogo1 = gameslogo1I;
export const gameslogo2 = gameslogo2I;
export const gameslogo3 = gameslogo3I;
export const gameslogo4 = gameslogo4I;
export const gameslogo5 = gameslogo5I;
export const gameslogo6 = gameslogo6I;
export const gameslogo7 = gameslogo7I;
export const gameslogo8 = gameslogo8I;
export const gameslogo9 = gameslogo9I;
export const gameslogo10 = gameslogo10I;
export const gameslogo11 = gameslogo11I;
export const gameslogo12 = gameslogo12I;
export const gameslogo13 = gameslogo13I;
export const gameslogo14 = gameslogo14I;
export const gameslogo15 = gameslogo15I;
export const gameslogo16 = gameslogo16I;
export const gameslogo17 = gameslogo17I;
export const gameslogo18 = gameslogo18I;
export const getstartbg = getstartbgI;
export const getstartillus = getstartillusI;
export const indexbannerbg = indexbannerbgI;
export const jackpotbg = jackpotbgI;
export const jackpoticon = jackpoticonI;
export const jackpotimage1 = jackpotimage1I;
export const jackpotimage2 = jackpotimage2I;
export const jackpotimage3 = jackpotimage3I;
export const jackpotimage4 = jackpotimage4I;
export const jackpotsecbg = jackpotsecbgI;
export const latestbetsbg = latestbetsbgI;
export const lotterybannerbg = lotterybannerbgI;
export const playerscircle = playerscircleI;
export const playersimg1 = playersimg1I;
export const playersimg2 = playersimg2I;
export const playersimg3 = playersimg3I;
export const populargamebg = populargamebgI;
export const populargameimage1 = populargameimage1I;
export const populargameimage2 = populargameimage2I;
export const populargameimage3 = populargameimage3I;
export const populargameimage4 = populargameimage4I;
export const populargameimage5 = populargameimage5I;
export const populargameimage6 = populargameimage6I;
export const populargameitem = populargameitemI;
export const preloader = preloaderI;
export const profileimage = profileimageI;
export const promotionsbannerbg = promotionsbannerbgI;
export const promotionsillus1 = promotionsillus1I;
export const promotionsillus2 = promotionsillus2I;
export const promotionsillus3 = promotionsillus3I;
export const promotionsillus4 = promotionsillus4I;
export const promotionsillus5 = promotionsillus5I;
export const promotionsillus6 = promotionsillus6I;
export const promotionsillus7 = promotionsillus7I;
export const promotionsillus8 = promotionsillus8I;
export const promotionsillus9 = promotionsillus9I;
export const referillus = referillusI;
export const refershape = refershapeI;
export const tableimage1 = tableimage1I;
export const tableimage2 = tableimage2I;
export const tableimage3 = tableimage3I;
export const tableimage4 = tableimage4I;
export const tableimage5 = tableimage5I;
export const tableimage6 = tableimage6I;
export const tableimage7 = tableimage7I;
export const tableimage8 = tableimage8I;
export const tableimage9 = tableimage9I;
export const tableimage10 = tableimage10I;
export const tournamentbannerbg = tournamentbannerbgI;
export const tournamentheadbg = tournamentheadbgI;
export const tournamentillus = tournamentillusI;
export const tournamentimg1 = tournamentimg1I;
export const tournamentimg2 = tournamentimg2I;
export const tournamentimg3 = tournamentimg3I;
export const tournamentimg4 = tournamentimg4I;
export const weeklylotterybg = weeklylotterybgI;

// Icon
export const SendIcon = SendIconI;
export const btcicon2 = btcicon2I;
export const btcicon3 = btcicon3I;
export const check = checkI;
export const countericon1 = countericon1I;
export const countericon2 = countericon2I;
export const dash = dashI;
export const downarrow = downarrowI;
export const emailicon = emailiconI;
export const etc = etcI;
export const facebook = facebookI;
export const featuresicon1 = featuresicon1I;
export const featuresicon2 = featuresicon2I;
export const featuresicon3 = featuresicon3I;
export const featuresicon4 = featuresicon4I;
export const gamestabicon1 = gamestabicon1I;
export const gamestabicon2 = gamestabicon2I;
export const gamestabicon3 = gamestabicon3I;
export const gamestabicon4 = gamestabicon4I;
export const gamestabicon5 = gamestabicon5I;
export const gamestabicon6 = gamestabicon6I;
export const gamestabicon7 = gamestabicon7I;
export const gamestabicon8 = gamestabicon8I;
export const howworksarrow1 = howworksarrow1I;
export const howworksarrow2 = howworksarrow2I;
export const howworksicon1 = howworksicon1I;
export const howworksicon2 = howworksicon2I;
export const howworksicon3 = howworksicon3I;
export const howworksicon4 = howworksicon4I;
export const howworksicon5 = howworksicon5I;
export const howworksicon6 = howworksicon6I;
export const infoicon1 = infoicon1I;
export const infoicon2 = infoicon2I;
export const instagram = instagramI;
export const playicon = playiconI;
export const plusicon = plusiconI;
export const prizeicon1 = prizeicon1I;
export const prizeicon2 = prizeicon2I;
export const prizeicon3 = prizeicon3I;
export const rightarrow = rightarrowI;
export const rightarrow2 = rightarrow2I;
export const searchicon = searchiconI;
export const searchicon2 = searchicon2I;
export const security = securityI;
export const sendicon = sendiconI;
export const tournamentgamesicon1 = tournamentgamesicon1I;
export const tournamentgamesicon2 = tournamentgamesicon2I;
export const trx = trxI;
export const twitter = twitterI;
export const whychooseicon1 = whychooseicon1I;
export const whychooseicon2 = whychooseicon2I;
export const whychooseicon3 = whychooseicon3I;
export const whychooseicon4 = whychooseicon4I;
export const whychooseicon5 = whychooseicon5I;
export const whychooseicon6 = whychooseicon6I;
export const winicon1 = winicon1I;
export const winicon2 = winicon2I;
export const winicon3 = winicon3I;
export const btcicon = btciconI;
